DELIMITER //

CREATE FUNCTION CALRECAREA(LENGTH FLOAT, WIDTH FLOAT)
RETURNS FLOAT
DETERMINISTIC
BEGIN
    RETURN LENGTH * WIDTH;
END //

DELIMITER ;

-- Function Call
SELECT CALRECAREA(5.5, 2.3) AS AREA;
