select @username;
CREATE DATABASE DATAANALYTICS;
USE DATAANALYTICS;
CREATE TABLE USERS (
  user_id INT PRIMARY KEY,
  user_name VARCHAR(100)
);
INSERT INTO USERS VALUES (1, 'Alice'), (2, 'Bob');
DELIMITER //
CREATE PROCEDURE GETALLUSERS()
BEGIN
	SELECT * FROM USERS;    
END//
CALL GETALLUSERS()